development:
  adapter: postgresql
  encoding: unicode
  database: seguridad_justicia_development
  pool: 5
  username: jparbros
  password: p0stgres

test:
  adapter: postgresql
  encoding: unicode
  database: seguridad_justicia_test
  pool: 5
  username: jparbros
  password: p0stgres

production:
  adapter: postgresql
  encoding: unicode
  database: seguridad_justicia_production
  pool: 5
  username: jparbros
  password: p0stgres
